apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudlab-facedetection
  namespace: facedetection
spec:
  selector:
    matchLabels:
      app: cloudlab-facedetection
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudlab-facedetection
    spec:
      containers:
      - name: cloudlab-facedetection
        image: zylean/cloudlab-facedetection:0873017
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
        env:
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        


