apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudlab-facedetection-backend
  namespace: facedetection
spec:
  selector:
    matchLabels:
      app: cloudlab-facedetection-backend
  replicas: null
  template:
    metadata:
      labels:
        app: cloudlab-facedetection-backend
    spec:
      containers:
      - name: cloudlab-facedetection-backend
        image: zylean/cloudlab-facedetection-backend:0affc6a
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5
        env:
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: password
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi


