apiVersion: v1
kind: Service
metadata:
  name: cloudlab-facedetection-backend-service
  namespace: facedetection
spec:
  type: NodePort
  selector:
    app: cloudlab-facedetection-backend
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30500
