apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudlab-facedetection
spec:
  selector:
    matchLabels:
      app: cloudlab-facedetection
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudlab-facedetection
    spec:
      containers:
      - name: cloudlab-facedetection
        image: zylean/cloudlab-facedetection:1.0
        ports:
        - containerPort: 5000
