apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: facedetection-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DnyKristof/CloudLab.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: facedetection
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

