apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudlab-facedetection-frontend
  namespace: facedetection
spec:
  selector:
    matchLabels:
      app: cloudlab-facedetection-frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: cloudlab-facedetection-frontend
    spec:
      containers:
      - name: cloudlab-facedetection-frontend
        image: zylean/cloudlab-facedetection-frontend:95814f8
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        


