apiVersion: v1
kind: Service
metadata:
  name: cloudlab-facedetection-frontend-service
  namespace: facedetection
spec:
  type: NodePort
  selector:
    app: cloudlab-facedetection-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30580
