apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: facedetection
spec:
  type: NodePort
  selector:
    app: mongodb
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30700
