name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: cloudlab-facedetection-backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Git SHA
        id: vars
        run: echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          cd src/backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${GIT_SHA::7} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${GIT_SHA::7} ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${GIT_SHA::7}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  build-frontend:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: cloudlab-facedetection-frontend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Git SHA
        id: vars
        run: echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          cd src/frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${GIT_SHA::7} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${GIT_SHA::7} ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${GIT_SHA::7}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  update-deployment-yaml:
    needs: [build-backend, build-frontend]
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME_FRONTEND: cloudlab-facedetection-frontend
      IMAGE_NAME_BACKEND: cloudlab-facedetection-backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Extract Git SHA
        run: echo "GIT_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Update backend deployment.yaml image tag
        run: |
          cd dev/backend
          sed -i "s|\(image: .*/${{ env.IMAGE_NAME_BACKEND }}:\)[^ ]*|\1${GIT_SHA::7}|" deployment.yaml
          cd ../frontend
          sed -i "s|\(image: .*/${{ env.IMAGE_NAME_FRONTEND }}:\)[^ ]*|\1${GIT_SHA::7}|" deployment.yaml
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add deployment.yaml
          git commit -m "Update image tag to ${GIT_SHA} in deployment.yaml"
          git push
